trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: demo-rahul
  resourceGroup: myapp-rg
  aksCluster: myapp
  acrName: rahulacr2026
  imageName: flaskapp
  tag: $(Build.BuildId)

steps:

# Install kubectl
- task: KubectlInstaller@0
  displayName: Install kubectl

# Login to Azure and ACR
- task: AzureCLI@2
  displayName: Login to Azure
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az account show
      az acr login --name $(acrName)

# Build Docker Image
- script: |
    docker build \
      -t $(acrName).azurecr.io/$(imageName):$(tag) .
  displayName: Build Docker Image

# Push Docker Image
- script: |
    docker push \
      $(acrName).azurecr.io/$(imageName):$(tag)
  displayName: Push Docker Image

# Deploy to AKS
- task: AzureCLI@2
  displayName: Deploy to AKS
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      az aks get-credentials \
        --resource-group $(resourceGroup) \
        --name $(aksCluster) \
        --overwrite-existing

      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml

      kubectl set image deployment/flask-app \
      flask-app=$(acrName).azurecr.io/$(imageName):$(tag)

      kubectl rollout status deployment/flask-app

      kubectl get pods

      kubectl get svc
